-- ============================================================
-- EMMA STUDIOS - SEED DATA
-- Run AFTER COMPLETE_SETUP.sql
-- ============================================================

-- 15 realistic UK creators
INSERT INTO emma_creators (
  id, display_name, slug, bio, short_bio, creator_type, specialty, skills,
  years_experience, hourly_rate, half_day_rate, full_day_rate,
  city, postcode, avatar_url, cover_image, portfolio_images, badges,
  rating, review_count, completed_bookings, returning_clients,
  is_featured, is_active, is_verified, status, instagram_url, website_url
) VALUES
(gen_random_uuid(), 'Marcus Cole', 'marcus-cole',
 'Award-winning fashion and editorial photographer based in East London. Regular contributor to Vogue, GQ, and Dazed. My work blends high fashion with street culture, creating images that feel both aspirational and authentic. I work with natural and studio light to create striking, editorial-grade imagery.',
 'Fashion and editorial photographer',
 'photographer', 'Fashion & Editorial',
 ARRAY['Fashion', 'Editorial', 'Portrait', 'Studio Lighting', 'Location Shoots'],
 12, 95.00, 280.00, 500.00, 'London', 'E2 8DP',
 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&h=600&fit=crop',
       'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=600&fit=crop',
       'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=600&fit=crop'],
 ARRAY['top_rated', 'verified', 'award'], 4.9, 156, 234, 89,
 true, true, true, 'approved', 'https://instagram.com/marcuscole', 'https://marcuscole.co.uk'),

(gen_random_uuid(), 'Priya Sharma', 'priya-sharma',
 'Music video and short film director/cinematographer. I have worked with artists signed to Universal, Sony, and independent labels across grime, drill, and R&B. My visual style is cinematic, moody, and narrative-driven.',
 'Music video cinematographer',
 'videographer', 'Music Videos',
 ARRAY['Music Videos', 'Short Films', 'Colour Grading', 'Drone', 'Narrative'],
 8, 110.00, 320.00, 580.00, 'London', 'N1 6NU',
 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&h=600&fit=crop'],
 ARRAY['verified', 'top_rated'], 4.8, 102, 187, 56,
 true, true, true, 'approved', 'https://instagram.com/priyasharma', NULL),

(gen_random_uuid(), 'Kwame Asante', 'kwame-asante',
 'Grammy-nominated mix engineer and producer. I have mixed tracks for Stormzy, Dave, and Little Simz. My studio setup includes a hybrid analogue/digital workflow that gives records warmth and punch.',
 'Grammy-nominated mix engineer',
 'audio_engineer', 'Music Production',
 ARRAY['Mixing', 'Mastering', 'Recording', 'Music Production', 'Vocal Production'],
 10, 85.00, 250.00, 450.00, 'London', 'SE15 4QN',
 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=600&fit=crop'],
 ARRAY['verified', 'award'], 4.9, 89, 156, 45,
 true, true, true, 'approved', NULL, 'https://kwameasante.com'),

(gen_random_uuid(), 'Elena Novak', 'elena-novak',
 'Commercial video editor specialising in brand content, product launches, and social campaigns. Clients include Nike, Gymshark, and Charlotte Tilbury. Fast turnarounds without compromising quality.',
 'Commercial video editor',
 'editor', 'Commercial Editing',
 ARRAY['Video Editing', 'Colour Correction', 'Motion Graphics', 'After Effects', 'DaVinci Resolve'],
 6, 75.00, 220.00, 400.00, 'Manchester', 'M1 2JQ',
 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=600&fit=crop'],
 ARRAY['verified'], 4.7, 67, 123, 34,
 false, true, true, 'approved', 'https://instagram.com/elenanovak', NULL),

(gen_random_uuid(), 'David Okonkwo', 'david-okonkwo',
 'Portrait and lifestyle photographer capturing authentic moments. Specialising in personal branding, headshots, and editorial portraiture for entrepreneurs, creatives, and corporate professionals.',
 'Portrait and branding photographer',
 'photographer', 'Portrait & Branding',
 ARRAY['Portrait', 'Lifestyle', 'Personal Branding', 'Headshots', 'Natural Light'],
 9, 80.00, 230.00, 420.00, 'London', 'SE1 9SG',
 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&h=600&fit=crop',
       'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=600&fit=crop'],
 ARRAY['verified', 'top_rated'], 4.8, 134, 198, 72,
 true, true, true, 'approved', 'https://instagram.com/davidokonkwo', 'https://davidokonkwo.com'),

(gen_random_uuid(), 'Sophie Chen', 'sophie-chen',
 'Corporate and event videographer with a cinematic approach. From conferences to product launches, I create polished content that elevates your brand. Full post-production included.',
 'Corporate videographer',
 'videographer', 'Corporate Video',
 ARRAY['Corporate Video', 'Events', 'Interviews', 'Live Streaming', 'Post-Production'],
 7, 90.00, 260.00, 480.00, 'Manchester', 'M2 4WU',
 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
 ARRAY['verified'], 4.7, 78, 145, 41,
 false, true, true, 'approved', NULL, 'https://sophiechen.co.uk'),

(gen_random_uuid(), 'Liam O''Brien', 'liam-obrien',
 'Podcast producer and audio engineer. From concept to distribution, I help brands and individuals launch professional podcasts. Equipped with broadcast-grade mics and acoustically treated spaces.',
 'Podcast producer',
 'audio_engineer', 'Podcast Production',
 ARRAY['Podcast Editing', 'Voiceover Recording', 'Audio Restoration', 'Mixing', 'Distribution'],
 5, 65.00, 190.00, 340.00, 'Birmingham', 'B1 1RD',
 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=600&fit=crop'],
 ARRAY['verified'], 4.6, 56, 98, 28,
 false, true, true, 'approved', 'https://instagram.com/liamobrien', NULL),

(gen_random_uuid(), 'Amara Williams', 'amara-williams',
 'Social media content creator and editor. I specialise in short-form vertical video for TikTok, Instagram Reels, and YouTube Shorts. Fast turnarounds, scroll-stopping edits.',
 'Short-form content editor',
 'editor', 'Social Media Content',
 ARRAY['Short Form', 'Reels', 'TikTok', 'Captions', 'Trending Audio'],
 4, 60.00, 175.00, 310.00, 'Leeds', 'LS1 4AP',
 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop'],
 ARRAY['verified'], 4.6, 91, 167, 52,
 false, true, true, 'approved', 'https://instagram.com/amarawilliams', NULL),

(gen_random_uuid(), 'Oliver Hart', 'oliver-hart',
 'Food and product photographer with over a decade of experience. Clients include Dishoom, Ottolenghi, and Waitrose. I bring a clean, appetising style to every shoot with meticulous attention to styling.',
 'Food and product photographer',
 'photographer', 'Food & Product',
 ARRAY['Food Photography', 'Product', 'Commercial', 'Styling', 'Flat Lay'],
 11, 90.00, 260.00, 480.00, 'London', 'WC2H 9JQ',
 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&h=600&fit=crop',
       'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop'],
 ARRAY['verified', 'award'], 4.9, 143, 212, 78,
 true, true, true, 'approved', 'https://instagram.com/oliverhart', 'https://oliverhart.co.uk'),

(gen_random_uuid(), 'Zara Hussain', 'zara-hussain',
 'Wedding and event videographer creating cinematic memories. South Asian wedding specialist with experience across Hindu, Muslim, and Sikh ceremonies. Two-person crew available.',
 'Wedding videographer',
 'videographer', 'Weddings & Events',
 ARRAY['Weddings', 'Events', 'Drone', 'Multi-Camera', 'Same Day Edits'],
 6, 100.00, 300.00, 550.00, 'Birmingham', 'B3 1SJ',
 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=600&fit=crop'],
 ARRAY['verified', 'top_rated'], 4.8, 112, 189, 67,
 true, true, true, 'approved', 'https://instagram.com/zarahussain', NULL),

(gen_random_uuid(), 'Noah Baptiste', 'noah-baptiste',
 'Live sound engineer and studio recording specialist. 13 years in the industry working with orchestras, bands, and solo artists. Technical rider and stage plot design included.',
 'Live sound engineer',
 'audio_engineer', 'Live Sound & Recording',
 ARRAY['Live Sound', 'Recording', 'System Design', 'Stage Management', 'Broadcast Audio'],
 13, 80.00, 240.00, 430.00, 'London', 'SE1 2TH',
 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=600&fit=crop'],
 ARRAY['verified', 'top_rated'], 4.8, 97, 176, 61,
 false, true, true, 'approved', NULL, 'https://noahbaptiste.com'),

(gen_random_uuid(), 'Isabella Martinez', 'isabella-martinez',
 'Documentary and long-form content editor. BAFTA-longlisted for short documentary work. I specialise in compelling narrative structure and emotional pacing.',
 'Documentary editor',
 'editor', 'Documentary & Long Form',
 ARRAY['Documentary', 'Long Form', 'Narrative', 'Sound Design', 'Colour Grade'],
 8, 80.00, 235.00, 420.00, 'Manchester', 'M4 4BF',
 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=800&h=600&fit=crop'],
 ARRAY['verified'], 4.7, 71, 134, 47,
 false, true, true, 'approved', 'https://instagram.com/isabellamartinez', NULL),

(gen_random_uuid(), 'Ethan Park', 'ethan-park',
 'Architectural and interior photographer working with property developers, estate agents, and interior designers. Matterport 3D scanning available. Drone-licensed.',
 'Architectural photographer',
 'photographer', 'Architecture & Interiors',
 ARRAY['Architecture', 'Interiors', 'Real Estate', 'Drone', 'Matterport 3D'],
 7, 75.00, 220.00, 400.00, 'London', 'SW1P 4QP',
 'https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
       'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop'],
 ARRAY['verified'], 4.7, 88, 162, 53,
 false, true, true, 'approved', NULL, 'https://ethanpark.co.uk'),

(gen_random_uuid(), 'Mia Thompson', 'mia-thompson',
 'Brand storytelling and social media video creator. I help DTC brands create scroll-stopping content that converts. From concept through to delivery, I handle everything.',
 'Brand content creator',
 'videographer', 'Brand & Social Content',
 ARRAY['Brand Content', 'UGC', 'Product Video', 'Behind The Scenes', 'Social Strategy'],
 5, 85.00, 250.00, 450.00, 'Leeds', 'LS2 7EE',
 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&h=600&fit=crop'],
 ARRAY['verified'], 4.7, 83, 151, 44,
 false, true, true, 'approved', 'https://instagram.com/miathompson', NULL),

(gen_random_uuid(), 'Lucas Rivera', 'lucas-rivera',
 'Full-service creative offering photography, videography, and post-production. Ideal for brands that want consistent visual identity across all content. Let me be your creative partner.',
 'Full-service creative',
 'photographer', 'Multi-Discipline',
 ARRAY['Photography', 'Videography', 'Editing', 'Content Strategy', 'Art Direction'],
 9, 95.00, 280.00, 520.00, 'London', 'EC2A 4NE',
 'https://images.unsplash.com/photo-1522556189639-b150ed9c4330?w=400&h=400&fit=crop',
 'https://images.unsplash.com/photo-1524678714210-9917a6c13c28?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1524678714210-9917a6c13c28?w=800&h=600&fit=crop'],
 ARRAY['verified', 'top_rated'], 4.9, 127, 203, 81,
 true, true, true, 'approved', 'https://instagram.com/lucasrivera', 'https://lucasrivera.co.uk');


-- 15 realistic UK studios
INSERT INTO emma_studios (
  id, name, slug, description, short_bio, studio_type,
  address, city, postcode, size, amenities, equipment,
  hourly_rate, half_day_rate, full_day_rate,
  cover_image, gallery_images, rating, review_count,
  is_featured, is_active, is_verified, status
) VALUES
(gen_random_uuid(), 'Shoreditch Daylight Studio', 'shoreditch-daylight-studio',
 'Stunning 2,500 sq ft daylight studio in the heart of Shoreditch. Floor-to-ceiling windows facing north provide beautiful, consistent natural light throughout the day. White-painted brick walls, polished concrete floors, and 4m ceilings. Perfect for fashion, portrait, and lifestyle shoots.',
 'Natural light studio in Shoreditch',
 'photography', '47 Rivington Street', 'London', 'EC2A 3QP', 'large',
 ARRAY['Natural Daylight', 'Kitchen', 'WiFi', 'Changing Room', 'Air Con', 'Loading Bay', 'Steamer'],
 ARRAY['Profoto D2 Kit', '6 Paper Backdrops', 'V-Flats', 'Reflectors', 'C-Stands'],
 65.00, 180.00, 340.00,
 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
       'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&h=600&fit=crop'],
 4.9, 187, true, true, true, 'approved'),

(gen_random_uuid(), 'Brixton Sound House', 'brixton-sound-house',
 'Professional recording studio with a vintage SSL 4000G console and world-class outboard gear. Two live rooms, isolation booth, and a spacious control room. Our in-house engineer can assist with sessions.',
 'SSL-equipped recording studio',
 'audio', '12 Coldharbour Lane', 'London', 'SW9 8LH', 'medium',
 ARRAY['Control Room', 'Live Room A', 'Live Room B', 'Iso Booth', 'Kitchen', 'Lounge', 'Parking'],
 ARRAY['SSL 4000G Console', 'Pro Tools HDX', 'Neumann U87', 'Vintage Compressors', 'Grand Piano'],
 80.00, 220.00, 400.00,
 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=600&fit=crop'],
 4.8, 142, true, true, true, 'approved'),

(gen_random_uuid(), 'Camden Film Works', 'camden-film-works',
 'Full-service video production facility with 3,000 sq ft shooting space. Features a permanent green screen wall, lighting grid, and on-site editing suite. Ideal for commercials, music videos, and branded content.',
 'Video production facility',
 'videography', '78 Camden High Street', 'London', 'NW1 0LT', 'large',
 ARRAY['Green Screen', 'Lighting Grid', 'WiFi', 'Kitchen', 'Editing Suite', 'Parking', 'Makeup Station'],
 ARRAY['ARRI Lighting Kit', 'Blackmagic Cameras', 'DaVinci Resolve Suite', 'Grip Equipment', 'Monitors'],
 75.00, 200.00, 380.00,
 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=600&fit=crop'],
 4.7, 156, true, true, true, 'approved'),

(gen_random_uuid(), 'Northern Quarter Loft', 'northern-quarter-loft',
 'Industrial-chic creative loft in Manchester NQ. Exposed brick, 5m ceilings, and huge Crittall windows. A favourite with fashion and lifestyle brands for its raw, editorial aesthetic.',
 'Industrial creative loft',
 'photography', '34 Tib Street', 'Manchester', 'M4 1LA', 'large',
 ARRAY['Natural Light', 'High Ceilings', 'WiFi', 'Kitchen', 'Changing Room', 'Freight Lift'],
 ARRAY['Backdrops', 'Elinchrom Lighting', 'Props Collection', 'Stands', 'Apple Boxes'],
 55.00, 150.00, 280.00,
 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop'],
 4.8, 129, false, true, true, 'approved'),

(gen_random_uuid(), 'Digbeth Audio Suite', 'digbeth-audio-suite',
 'Boutique recording studio in Birmingham creative quarter. Analog warmth meets digital precision. Neve preamps, vintage synths, and a beautifully treated live room.',
 'Boutique recording studio',
 'audio', '67 Gibb Street', 'Birmingham', 'B9 4AA', 'small',
 ARRAY['Control Room', 'Live Room', 'Vocal Booth', 'WiFi', 'Kitchen', 'Artist Lounge'],
 ARRAY['Neve 1073 Preamps', 'Pro Tools', 'Vintage Synths', 'Neumann TLM103', 'Yamaha NS10s'],
 60.00, 170.00, 310.00,
 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800&h=600&fit=crop'],
 4.6, 98, false, true, true, 'approved'),

(gen_random_uuid(), 'Calls Landing Studio', 'calls-landing-studio',
 'Modern content creation studio on Leeds waterfront. Purpose-built for influencers, podcasters, and social brands. Multiple set-ups ready to go, no setup time wasted.',
 'Content creation studio',
 'videography', '36 The Calls', 'Leeds', 'LS2 7EW', 'medium',
 ARRAY['Ring Lights', 'Multiple Backdrops', 'WiFi', 'Teleprompter', 'Props Wall', 'Changing Room'],
 ARRAY['Sony FX3', 'LED Panels', 'Rode Mics', 'Gimbal', 'Editing iMac'],
 50.00, 140.00, 260.00,
 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=600&fit=crop'],
 4.7, 114, false, true, true, 'approved'),

(gen_random_uuid(), 'Hackney Whites', 'hackney-whites',
 'Intimate 800 sq ft white-box studio with beautiful north-facing daylight. Clean, minimal aesthetic perfect for beauty, product, and portrait photography. No distractions, just great light.',
 'White box daylight studio',
 'photography', '89 Mare Street', 'London', 'E8 4RG', 'small',
 ARRAY['Natural Light', 'Changing Room', 'WiFi', 'Kitchen', 'Blackout Blinds'],
 ARRAY['Godox AD600', 'Paper Backdrops', 'Beauty Dish', 'V-Flats', 'Reflectors'],
 55.00, 150.00, 280.00,
 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop'],
 4.8, 167, false, true, true, 'approved'),

(gen_random_uuid(), 'Salford Sessions', 'salford-sessions',
 'Music recording and rehearsal space near MediaCityUK. Three rooms: main recording studio, rehearsal room, and podcast booth. Session musicians network available.',
 'Recording and rehearsal space',
 'audio', '23 Chapel Street', 'Manchester', 'M3 5LE', 'medium',
 ARRAY['Recording Studio', 'Rehearsal Room', 'Podcast Booth', 'WiFi', 'Kitchen', 'Parking'],
 ARRAY['Backline (Drums, Amps)', 'Mics', 'Focusrite Console', 'PA System', 'In-Ear Monitors'],
 60.00, 170.00, 320.00,
 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=600&fit=crop'],
 4.7, 134, false, true, true, 'approved'),

(gen_random_uuid(), 'Custard Factory Studios', 'custard-factory-studios',
 'Large-scale film and video production facility in Birmingham Custard Factory. 4,000 sq ft with infinity cove, pre-lit grid, and on-site post-production. Major brand shoots and commercials welcome.',
 'Large-scale production studio',
 'videography', '99 Gibb Street', 'Birmingham', 'B9 4AA', 'large',
 ARRAY['Infinity Cove', 'Lighting Grid', 'WiFi', 'Kitchen', 'Parking', 'Loading Bay', 'Green Room'],
 ARRAY['ARRI Skypanels', 'RED Camera Package', 'Full Grip Kit', 'DIT Station', 'Colour Suite'],
 85.00, 240.00, 450.00,
 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=600&fit=crop'],
 4.9, 178, true, true, true, 'approved'),

(gen_random_uuid(), 'Old Street Multi-Space', 'old-street-multi-space',
 'Versatile 2,000 sq ft creative space near Old Street roundabout. Fully configurable - daylight or blackout, photo or video, product or fashion. The chameleon studio.',
 'Versatile creative space',
 'multipurpose', '101 Old Street', 'London', 'EC1V 9NR', 'large',
 ARRAY['Daylight + Blackout', 'WiFi', 'Kitchen', 'Changing Rooms', 'Parking', 'Steamer', 'Iron'],
 ARRAY['Broncolor Lighting', 'Paper + Fabric Backdrops', 'Props', 'Audio Equipment', 'Tripods'],
 70.00, 195.00, 370.00,
 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&h=600&fit=crop'],
 4.8, 152, true, true, true, 'approved'),

(gen_random_uuid(), 'Greenwich Product Lab', 'greenwich-product-lab',
 'Clean white studio optimised for product and e-commerce photography. Overhead rig, turntable, and lightbox included. Ideal for Amazon, Shopify, and catalogue shoots.',
 'Product photography studio',
 'photography', '34 Greenwich High Road', 'London', 'SE10 8JL', 'medium',
 ARRAY['Overhead Rig', 'Product Turntable', 'WiFi', 'Kitchen', 'Storage'],
 ARRAY['Profoto Pro-11', 'Light Tent', 'Macro Lens Kit', 'Tethering Station', 'Styling Kit'],
 60.00, 165.00, 310.00,
 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop'],
 4.7, 121, false, true, true, 'approved'),

(gen_random_uuid(), 'Jewellery Quarter Podcast Hub', 'jq-podcast-hub',
 'Purpose-built podcast studio in Birmingham JQ. Fully soundproofed, broadcast-ready mics, and multi-camera video podcast setup. Remote guest integration via Riverside.fm.',
 'Professional podcast studio',
 'audio', '78 Vyse Street', 'Birmingham', 'B18 6HA', 'small',
 ARRAY['Soundproof Room', 'WiFi', 'Kitchen', 'Green Room', 'Video Podcast Setup'],
 ARRAY['Shure SM7B Mics', 'RODECaster Pro II', 'PTZ Cameras', 'Headphones', 'Riverside.fm'],
 45.00, 125.00, 230.00,
 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=600&fit=crop'],
 4.6, 87, false, true, true, 'approved'),

(gen_random_uuid(), 'Headingley Film Lab', 'headingley-film-lab',
 'Video production and editing facility near Leeds university campus. Green screen, interview setup, and three editing suites with DaVinci Resolve. Student discounts available.',
 'Video production lab',
 'videography', '45 Otley Road', 'Leeds', 'LS6 3AA', 'medium',
 ARRAY['Green Screen', 'Editing Suites', 'WiFi', 'Kitchen', 'Parking', 'Student Lounge'],
 ARRAY['Sony FX6', 'LED Panels', 'DaVinci Resolve Workstations', 'Sound Booth', 'Colour Monitor'],
 55.00, 155.00, 290.00,
 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=600&fit=crop'],
 4.8, 145, false, true, true, 'approved'),

(gen_random_uuid(), 'Kings Cross Studio', 'kings-cross-studio',
 'Central London studio 2 minutes from Kings Cross station. 1,200 sq ft with natural and artificial light options. Popular with agencies and magazines for its convenience and versatility.',
 'Central photo studio',
 'photography', '12 York Way', 'London', 'N1 9AA', 'medium',
 ARRAY['Natural Light', 'Blackout', 'WiFi', 'Kitchen', 'Parking', 'Makeup Mirror'],
 ARRAY['Elinchrom ELC 500', 'Backdrops', 'Props', 'Steamer', 'Full-Length Mirror'],
 62.00, 170.00, 320.00,
 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop'],
 4.7, 138, false, true, true, 'approved'),

(gen_random_uuid(), 'Soho Production House', 'soho-production-house',
 'Premium multi-purpose production facility in the heart of Soho. Three studios, post-production suite, client lounge, and on-site catering. White-glove service for high-end commercial work.',
 'Premium production house',
 'multipurpose', '56 Wardour Street', 'London', 'W1D 6QW', 'large',
 ARRAY['3 Studios', 'Post Suite', 'Client Lounge', 'Catering', 'Valet Parking', 'Hair & Makeup'],
 ARRAY['Phase One Camera System', 'ARRI Lighting', 'Dolby Atmos Mix Room', 'Full Grip', 'Colour Suite'],
 95.00, 270.00, 500.00,
 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&h=600&fit=crop',
 ARRAY['https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=600&fit=crop'],
 4.9, 201, true, true, true, 'approved');


-- 20 packages (10 studio, 10 creator)
INSERT INTO emma_packages (id, studio_id, name, description, duration_hours, price, includes, is_popular, is_active)
VALUES
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'shoreditch-daylight-studio' LIMIT 1),
   'Half Day Shoot', 'Morning or afternoon session with full studio access', 4, 180,
   ARRAY['4 hour studio access', 'Full lighting kit', 'Backdrop options', 'WiFi', 'Changing room'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'shoreditch-daylight-studio' LIMIT 1),
   'Full Day Exclusive', 'Exclusive full-day access to the entire studio', 8, 340,
   ARRAY['8 hour exclusive access', 'All equipment included', 'Kitchen access', 'Steamer', 'Early access from 7am'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'brixton-sound-house' LIMIT 1),
   'Tracking Session', 'Recording session with engineer', 4, 280,
   ARRAY['4 hour studio time', 'In-house engineer', 'Pro Tools session', 'Basic rough mix'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'brixton-sound-house' LIMIT 1),
   'Full Production Day', 'Complete recording, mixing, and mastering', 10, 600,
   ARRAY['10 hour session', 'Dedicated engineer', 'Full mixing', 'Mastering', 'Unlimited revisions', 'Stem exports'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'camden-film-works' LIMIT 1),
   'Content Creator Package', 'Quick video content session', 4, 250,
   ARRAY['4 hour studio', 'Green screen', 'Basic lighting', 'Teleprompter', 'Self-operated'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'camden-film-works' LIMIT 1),
   'Commercial Production', 'Full day production with all equipment', 10, 700,
   ARRAY['10 hour access', 'Full ARRI lighting', 'Grip equipment', 'Editing suite access', 'Production assistant'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'northern-quarter-loft' LIMIT 1),
   'Flex Session', 'Flexible half-day booking', 4, 150,
   ARRAY['4 hour access', 'Configurable space', 'Basic equipment', 'WiFi', 'Kitchen'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'northern-quarter-loft' LIMIT 1),
   'Full Day Takeover', 'Complete loft access for the day', 10, 380,
   ARRAY['10 hour exclusive', 'All equipment', 'Kitchen access', 'Parking for 2', 'Overnight gear storage'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'soho-production-house' LIMIT 1),
   'Premium Half Day', 'White-glove studio experience', 4, 380,
   ARRAY['4 hour premium access', 'High-end equipment', 'Dedicated assistant', 'Catering included'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_studios WHERE slug = 'soho-production-house' LIMIT 1),
   'VIP Full Day', 'The ultimate production experience', 10, 850,
   ARRAY['10 hour VIP access', 'All premium equipment', 'Production assistant', 'Gourmet catering', 'Valet parking', 'Post suite access'], true, true);

INSERT INTO emma_packages (id, creator_id, name, description, duration_hours, price, includes, is_popular, is_active)
VALUES
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'marcus-cole' LIMIT 1),
   'Portrait Session', 'Professional portrait photography', 2, 190,
   ARRAY['2 hour session', '20 retouched images', 'Online gallery', 'Print rights', 'Outfit guidance'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'marcus-cole' LIMIT 1),
   'Editorial Shoot', 'Full editorial photography experience', 5, 450,
   ARRAY['5 hour session', '50 retouched images', 'Creative direction', 'Mood board', '3 outfit changes', 'Online gallery'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'priya-sharma' LIMIT 1),
   'Performance Capture', 'Music video performance shoot', 4, 400,
   ARRAY['4 hour shoot', 'Single camera setup', 'Basic edit', 'Colour grade', '1 revision round'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'priya-sharma' LIMIT 1),
   'Full Music Video', 'Complete music video production', 8, 800,
   ARRAY['8 hour shoot', 'Multi-camera', 'Full edit', 'Colour grade', 'VFX', 'BTS content', '3 revision rounds'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'kwame-asante' LIMIT 1),
   'Single Mix', 'Professional track mixing', 2, 170,
   ARRAY['Full mix', 'Stem exports', '2 revision rounds', '48hr turnaround'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'kwame-asante' LIMIT 1),
   'EP Package', 'Multi-track EP mixing and mastering', 10, 600,
   ARRAY['Up to 5 tracks', 'Full mixing', 'Mastering', 'Unlimited revisions', 'Stem exports', 'Distribution-ready files'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'david-okonkwo' LIMIT 1),
   'Headshot Session', 'Professional headshots', 1, 120,
   ARRAY['1 hour session', '5 retouched headshots', 'LinkedIn-optimised', 'Same-week delivery'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'david-okonkwo' LIMIT 1),
   'Brand Story Package', 'Full personal branding shoot', 4, 380,
   ARRAY['4 hour session', '30 images', 'Multiple locations', 'Style consultation', 'Social media crops', 'Brand guidelines'], true, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'lucas-rivera' LIMIT 1),
   'Content Bundle', 'Photo + video combo', 4, 340,
   ARRAY['4 hour session', '15 photos', '1 short-form video', 'Social media edits', 'Same-week delivery'], false, true),
  (gen_random_uuid(), (SELECT id FROM emma_creators WHERE slug = 'lucas-rivera' LIMIT 1),
   'Full Creative Package', 'Complete content creation', 8, 680,
   ARRAY['8 hour session', '40 photos', '3 videos', 'Full editing', 'Social media package', 'Content calendar'], true, true);
